README Rework
LucidVR/opengloves-driver pull request #173
Opened 2022-01-13 03:23 UTC by ElectronicsArchiver

- Formatting / Refactoring
- Separation Of Content
- Fixes, Links, Badges

2022-01-14 14:25 UTC, danwillm requested changes
Thanks for this, just a few comments 👍

2022-01-14 14:25 UTC, danwillm commented on docs/Limitations.md
> +     *you specify the properties & settings of your controller.*
```suggestion
If you want to implement your own device and use the utilities that OpenGloves provides (such as bone calculations and communication), create your own class that is derived from [`DeviceDriver`], and implement `StartingDevice`, `SetupProps`, `HandleInput` and `StoppingDevice`.
```

2022-01-14 14:25 UTC, danwillm commented on docs/Limitations.md
> +Due to how **OpenVR** wworks, inputs cannot be set ***dynamically***.
`wworks`.

2022-01-14 14:25 UTC, danwillm commented on docs/Limitations.md
> +     *custom device with a different input profile.*
can we reorder this, just so it makes a little more sense?
```suggestion
Our inputs for `Index Controller Emulated Devices` are ***fixed*** to that of the index controller, and cannot have custom inputs.

**➔**  *However, you can define your own inputs in a* <br>
     ***custom device** with a different input profile.*
```

2022-01-14 14:25 UTC, danwillm commented on README.md
> +Glove hardware providing an **[Open Interface]**.
```suggestion
A general purpose **SteamVR** driver for **DIY** VR <br>
(Glove) hardware, which provides an **[Open Interface]** for anyone wanting to connect their own hardware to SteamVR,
```

2022-01-14 14:25 UTC, danwillm commented on README.md
> +    *➜ Joystick | X | Y*
joysticks also have a click
```suggestion
    *➜ Joystick | X | Y | Click*
```

2022-01-14 14:25 UTC, danwillm commented on README.md
> +The **[Steam]** version of **OpenGloves** also provides you a **[UI]**.
Perhaps?
```suggestion
When **OpenGloves** is downloaded on **[Steam]**, it comes with a **[UI]** for configuring driver related features.
```

2022-01-14 14:25 UTC, danwillm commented on docs/Compatibility.md
> +**You made your own hardware, let us know!**
```suggestion
 **Made your own hardware? Let us know!**
```

2022-01-14 14:25 UTC, danwillm commented on docs/Compatibility.md
> +`Encoding Schemes` & `Communication Methods`.
```suggestion
To make your own hardware compatible with **OpenGloves**, <br>
refer to the **[Driver Input]** page, which <br>
provides information on making your hardware compatible.

2022-01-14 14:25 UTC, danwillm commented on docs/Compatibility.md
> +Our own **[Firmware]** for the **OpenGloves** is <br>
```suggestion
Our own **[Firmware]** that is comatible with **OpenGloves** is <br>

2022-01-14 14:25 UTC, danwillm commented on docs/Compatibility.md
> +Unfortunately this selection is **[More Limited]**.
```suggestion
Unfortunately, game compatibility with Force Feedback is **[More Limited]**.<br>
If you'd like to make your game/mod compatible with Force Feedback, refer to this wiki page
```
(+ link to https://github.com/LucidVR/opengloves-driver/wiki/Integrating-Force-Feedback)

2022-01-15 13:56 UTC, danwillm approved these changes

2022-01-22 23:46 UTC, lucas-vrtech approved these changes
Looks great :)

2022-01-22 23:47 UTC, merged